---
title: "using crostalk"
output: html_document
---

```{r loadDataETC, include=FALSE}
library(tidyverse)     # tidy data, includes readr
library(leaflet)       # GIS/mapping -- An HTML Widget
library(DT)            # DataTables provides filtering, pagination, sorting, and many other features in the tables.  An HTML Widget
library(crosstalk)     # interactive linking between HTML widgets
```

```{r, include=FALSE}
starbucks <- read_csv("https://opendata.socrata.com/api/views/ddym-zvjk/rows.csv")

starbucks  %>%  
  filter(State == "NC") -> starbucks
```

## DataTable
```{r datatable}

sd <- starbucks  %>%  
  select(Name, `Facility ID`, Location, Latitude, Longitude) %>% 
  rename(fid = `Facility ID`, latitude = Latitude, longitude = Longitude)

# sd %>% 
#   datatable()

datatable(sd, extensions="Scroller", style="bootstrap", width="100%", 
            options=list(deferRender=TRUE,  scrollY=300, scroller=TRUE))
```

## Map
```{r leaflet map}

leaflet(sd) %>% addTiles() %>% addMarkers(popup = starbucks$Name)

```


## Sharefunction

go here to start sharing with crossTalk
```{r share-talk}
sharebux <- SharedData$new(sd)


datatable(sharebux, extensions="Scroller", style="bootstrap", width="100%", 
            options=list(deferRender=TRUE,  scrollY=300, scroller=TRUE))
leaflet(sharebux) %>% addTiles() %>% addMarkers(popup = starbucks$Nam)

```
